<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <CodePage>65001</CodePage>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\Icon\app.ico</ApplicationIcon>
    <AssemblyName>GaeulDesktopPet</AssemblyName>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <NoWarn>$(NoWarn);WFAC010;NU1900</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\Icon\icon.png" />
    <Resource Include="Assets\Icon\app.ico" />
    <Content Include="Assets\Sprites\01_gaeul_kitsch\**\*.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
</Project>
